server:
  port: ${PORT:40400}
  servlet:
    context-path: /auth
spring:
  profiles:
      active: dev
  application:
    name: xc-service-ucenter-auth
    http:
       multipart:
          maxFileSize: 5Mb
          maxRequestSize: 60Mb




