server:
  port: ${PORT:31200}
spring:
 profiles:
      active: dev
 application:
   name: xc-service-manage-course
   http:
      multipart:
         maxFileSize: 5Mb
         maxRequestSize: 60Mb






