server:
  port: 12001

spring:
  application:
    name: silkroad-config
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: svn://39.105.60.119/open/config/trunk
          username: liutianshu
          password: liutianshu0327
          search-paths: trunk/**

logging:
  level:
    cn.silucaihong: debug
  file: /var/logs/${spring.application.name}-${server.port}.log

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11001/eureka/